# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
spec:
  selector:
    app: {{APP_NAME}}
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
